[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "authz-analyzer"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
test = [
    "cython",
    "dd==0.6.0",
    "hypothesis",
    "pytest",
    "wheel",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]
